### ISSUE TITLE
When can the training data be available?

### ISSUE THREAD

**Issue by flyingzhao** [anhttran/3dmm_cnn#1]
It is a definitely grat work. I am wondering when the trainging data  can be available? Looking forword your training data!

**Comment by TalHassner** [comment]
@flyingzhao, thank for your feedback! We are planning a number of updates with more data and functionality, but I don't expect these to include the data we used for training. 

You can find details on how we produced the training data, in the paper, available from the [project webpage](http://www.openu.ac.il/home/hassner/projects/CNN3DMM/).
