### ISSUE TITLE
Full head model

### ISSUE THREAD

**Issue by samsgates** [anhttran/3dmm_cnn#10]
how to create full head model for training dataset( same like BFM, but full head)
output will be full head 3d model only mesh, no color or texture

**Comment by anhttran** [comment]
Hi,
To use the full head, you can change trimBaselFace.py:
1. Do not use vertex_indices3, which is for mesh trimming
2. Change this line of code:
`faces = mod_struct.faces`
to
```
faces = model['tl']
my_array[:,[1, 2]] = my_array[:,[2, 1]]
```

Note that the landmark indices will be outdated. Though, we do not use these landmarks in this release.

**Comment by samsgates** [comment]
i didn't seen the below line
======
faces = mod_struct.faces
======

any way i have changed "trimBaselFace.py" code as your instruction. but full head model not generated in output, i got same result like half head model.

I have attached edited file as "trim.py", please update send me back with changes required for generate full head


[trim.py.zip](https://github.com/anhttran/3dmm_cnn/files/1076620/trim.py.zip)

**Comment by dingtiandu** [comment]
Hi.
I have meet the same problem.Have you solved it???(i didn't seen the below line in code

faces = mod_struct.faces)

**Comment by dingtiandu** [comment]
Hi
Your result 3d ALPHA only has 99 numbers.Can I get a ALPHA of 199 numbers, just like the old version of BFM dataset?
Hoping for replying.

**Comment by anhttran** [comment]
@samsgates My bad. I looked into a wrong code.
Please find the updated code for full head model below.
```
##MATLAB: BFM.shapeMU = model.shapeMU(vertex_indices3,:)/1000;
shapeMU = model['shapeMU']/1000;
##MATLAB: BFM.shapeMU(1:3:end) = BFM.shapeMU(1:3:end) + mod_struct.tx;
shapeMU[0:-1:3] = shapeMU[0:-1:3] +  mod_struct.tx
##MATLAB: BFM.shapeEV = model.shapeEV(1:99)/1000;
shapeEV = model['shapeEV'][0:99]/1000.
##MATLAB BFM.shapePC = model.shapePC(vertex_indices3,1:99);
shapePC = model['shapePC'][:,0:99]
##MATLAB  BFM.texMU = model.texMU(vertex_indices3,:);
texMU = model['texMU']
##MATLAB  BFM.texPC = model.texPC(vertex_indices3,1:99);
texPC = model['texPC'][:,0:99];
##MATLAB  BFM.texEV = model.texEV(1:99);
texEV = model['texEV'][0:99];
innerLandmarkIndex = mod_struct.innerLandmarkIndex
outerLandmarkIndex = mod_struct.outerLandmarkIndex

#% Faces
faces_tmp = model['tl']
#faces = faces_tmp,[2 1 3])
faces = np.dstack([faces_tmp[:,1], faces_tmp[:,0], faces_tmp[:,2]])
faces = faces[0]
```


@dingtiandu We only use 99 parameters for shape & texture since they are good enough for face recognition purpose according to Blanz's paper:
http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=1227983

**Comment by samsgates** [comment]
Thanks for your response
