### ISSUE TITLE
How to train the model and define the label？

### ISSUE THREAD

**Issue by ChuckGithub** [anhttran/3dmm_cnn#13]
It's very kind of you to share the model.
I'am a new guy to 3D face reconstruction and I want to train my own model, what should i do?
Looking forward to your reply.

**Comment by anhttran** [comment]
Sorry for my late reply. You can find our description of how to get training labels in section 3.1, and how to train the network in section 3.2:
[https://arxiv.org/abs/1612.04904](url)

Best,
Anh

**Comment by ChuckGithub** [comment]
Thank you for your answer, but I have another question is how to use the generated 3DMM model as a label and on behalf of this category. That is to say which 3DMM parameters are used as a training label.

**Comment by anhttran** [comment]
We used 99 shape parameters + 99 texture parameters. They form 198D vectors, which were used as training labels.

**Comment by ChuckGithub** [comment]
OK,Thank you,This information can be obtained from your paper, how to choose the 198D vectors from the 3DMM model,and what are the specific requirements for these parameters.

**Comment by anhttran** [comment]
For each CASIA image, we estimate 3DMM parameters, using the traditional method. Each parameter is a floating number in range [-3, 3]. Then, we computed weighted average of these parameters from all images of the same subject, and use the pooled parameters to for a 198D ground-truth label.

In CNN training, we used 1 LMDB to store the images, and 1 LMDB to store the corresponding labels.

**Comment by ChuckGithub** [comment]
OK,Thank you,This process is clear.

**Comment by WWWJL** [comment]
> OK,Thank you,This process is clear.

hi,can you train about your own dataset ?
