### ISSUE TITLE
"freeglut (c):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow" when running the testModel_PoseExpr.py demo.

### ISSUE THREAD

**Issue by medivhna** [anhttran/3dmm_cnn#14]
```
> Prepare image ~/3dmm_cnn/demoCode/data/1.jpg:
    Number of faces detected: 1
> CNN Model loaded to regress 3D Shape and Texture!
*****************************************
** Caffe loading    : 1.468 s
** Image cropping   : 2.259 s
** 3D Modeling      : 1.975 s
*****************************************
> Pose & expression estimation
load ../3DMM_model/BaselFaceModel_mod.h5
freeglut (c):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow
```
I found the same issue on google, but cannot work. Is there a trouble shooting about it?

**Comment by medivhna** [comment]
I get a solution of this issue.

I run the demo in a VNC Gnome GUI. The function of OpenGL is limited in this environment. Just run the demo in CUI environment can avoid this error.

**Comment by anhttran** [comment]
It is great. I am glad that you found the solution.

**Comment by wfly1998** [comment]
@medivhna But...as the `README.md` says that the result should be shown in a window, how to see the content in that window in CLI environment?
