### ISSUE TITLE
H5Cpp.h

### ISSUE THREAD

**Issue by xkx0430** [anhttran/3dmm_cnn#15]
I like your paper very much.
but....
Can you tell me why?

fatal error: H5Cpp.h: No such file or directory
compilation terminated.
modules/PoseExpr/CMakeFiles/PoseExprLib.dir/build.make:110: recipe for target 'modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/BaselFace.cpp.o' failed
make[2]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/BaselFace.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all' failed
make[1]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I use ubuntu 16.04, and have installed libhdf5-dev and libhdf5-serial-dev
thank you

**Comment by xkx0430** [comment]
Hey, I have compiled it, as follows.

# Find HDF5
find_package(HDF5 REQUIRED)
message("HDF5 information:")
message("HDF5_INCLUDE_DIRS: ${HDF5_INCLUDE_DIRS}")
message("HDF5_LIBRARIES: ${HDF5_LIBRARIES}")
INCLUDE_DIRECTORIES(${HDF5_INCLUDE_DIRS})
target_link_libraries(TestVisualization PoseExprLib ${HDF5_LIBRERIES})

Is this right?

**Comment by anhttran** [comment]
Have you installed libhdf5-dev? Can you check whether H5Cpp.h exists in /usr/include?

**Comment by tobyclh** [comment]
Hello, this problem also happens to me. and the file is in /usr/include/hdf5/serial/H5Cpp.h

**Comment by anhttran** [comment]
Dear all,

You can set CPATH before running cmake:

*export CPATH=/usr/include/hdf5/serial/**:$CPATH*
>

Hope it help.
Best regards,
Anh
