### ISSUE TITLE
HDF5 object not found

### ISSUE THREAD

**Issue by kiakaviani** [anhttran/3dmm_cnn#16]
Congratulations, nice work
I am trying to run your code on windows, everything works fine on python side, trimBaselFace.py successfully create modified baselface models, and testModel_PoseExpr.py works prefect.
But I am getting following error when I want to run your cpp pose find example using visual stdio.
It seems modified baselface model created by python can not be read in cpp hdf5.
It seems hdf5 is searching for object name that is not in ascii form (line #004) :

HDF5-DIAG: Error detected in HDF5 (1.8.19) thread 0:
  #000: C:\Users\buildbot\Buildbot\hdf518-StdRelease-code-vs14\build\hdfsrc\src\
H5D.c line 356 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: C:\Users\buildbot\Buildbot\hdf518-StdRelease-code-vs14\build\hdfsrc\src\H5Gloc.c line 428 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: C:\Users\buildbot\Buildbot\hdf518-StdRelease-code-vs14\build\hdfsrc\src\H5Gtraverse.c line 859 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: C:\Users\buildbot\Buildbot\hdf518-StdRelease-code-vs14\build\hdfsrc\src\H5Gtraverse.c line 639 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #004: C:\Users\buildbot\Buildbot\hdf518-StdRelease-code-vs14\build\hdfsrc\src\H5Gloc.c line 383 in H5G_loc_find_cb(): object '@>┐⌠↔' doesn't exist
    major: Symbol table
    minor: Object not found

**Comment by anhttran** [comment]
Thank you for your interest on our work. 
I have not tried my C++ code on Windows. Have you generated BaselFaceModel_mod.h5?

**Comment by kiakaviani** [comment]
Yes, as I mentioned trimBaselFace.py runs with no errors and it generates BaselFaceModel_mod.h5.
I think there is some problem with HDF5 in windows.
Thank you for your answer, I'll try more to fix it on windows first, if no success, I will migrate to ubuntu.
