### ISSUE TITLE
caffe error..!

### ISSUE THREAD

**Issue by singireddysravankumar** [anhttran/3dmm_cnn#19]
Hii,
  I am new to python when i am trying to install caffe i am getting error when running make all,make pycaffe.The error is 
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
.build_release/src/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
.build_release/src/caffe/proto/caffe.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:
.build_release/src/caffe/proto/caffe.pb.h:23:35: fatal error: google/protobuf/arena.h: No such file or directory
compilation terminated.
Makefile:588: recipe for target '.build_release/src/caffe/proto/caffe.pb.o' failed
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1

Please any one can help 
Thanks in advance

**Comment by anhttran** [comment]
Dear,

You may have multiple versions of google-protobuf.You can use "locate" to
check location of your google-protobuf libraries (e.g. locate
libprotobuf.so), then config caffe to use the same google-protobuf version
in compiling.

By the way, you should post your question in Caffe's project repository. It
is more relevant.

Best regards,
Anh

**Comment by iacopomasi** [comment]
@singireddysravankumar Even better, do not open an issue in caffe github, but use Caffe google forum to ask quesitons https://groups.google.com/forum/#!forum/caffe-users

Closing this issue.
