### ISSUE TITLE
"H5Cpp.h: No such file or directory" error once.

### ISSUE THREAD

**Issue by ronyuzhang** [anhttran/3dmm_cnn#20]
hi, 
 i  have already set "export CPATH=/usr/include/hdf5/serial/**:$CPATH" , but still wrong.

===================
/home/demo/3dmm_cnn/modules/PoseExpr/src/BaselFace.cpp:19:19: fatal error: H5Cpp.h: No such file or directory
compilation terminated.
modules/PoseExpr/CMakeFiles/PoseExprLib.dir/build.make:110: recipe for target 'modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/BaselFace.cpp.o' failed
make[2]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/BaselFace.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all' failed
make[1]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by anhttran** [comment]
Your HDF5 headers may be in another location. You can run "locate H5Cpp.h" to find the correct path.
Best,
Anh

**Comment by wantongtang** [comment]
solved this problem  by export CPATH
export CPATH=/usr/include/hdf5/serial/

**Comment by valbi** [comment]
I still have exactly the same problem.
I tried type " export CPATH=/usr/include/hdf5/serial/ " before cmake
and tried too modify bashrc to add the same line. But the error is not resolved.

"locate H5Cpp.h" is well in /usr/include/hdf5/serial/H5Cpp.h 
"find /usr -iname "*hdf5.h*" give the folowing paths : 
/usr/include/hdf5/serial/hdf5.h
/usr/include/opencv2/flann/hdf5.h
/usr/local/include/opencv2/flann/hdf5.h

I'm looking for issues concerning H5Cpp.h but I am still stuck.
