### ISSUE TITLE
The input of multi images for one face model

### ISSUE THREAD

**Issue by ChenFengYe** [anhttran/3dmm_cnn#22]
I am looking a method to generate one face model by feeding multi-images of one person. does your code support that? Hope for your replying.
PS: I see that you use multi-images of one man to train the network, so I wonder the similar input to get one model.

**Comment by anhttran** [comment]
You can run the network on each input image, then combine the estimated 3D models together. This method was described in the part of "Multi image 3DMM fitting" in section 3.1. 

A network that takes multiple images of the same subject as input is not in the scope of our paper. However, it can be an interesting research topic.

Best,
Anh
