### ISSUE TITLE
what is /home/anh anyway?

### ISSUE THREAD

**Issue by QuantumLiu** [anhttran/3dmm_cnn#23]
```
make[2]: *** No rule to make target '/home/anh/Downloads/dlib-19.4/shared_build/dlib/libdlib.so', needed by 'bin/TestVisualization'。 停止。
CMakeFiles/Makefile2:196: recipe for target 'config/CMakeFiles/TestVisualization.dir/all' failed
make[1]: *** [config/CMakeFiles/TestVisualization.dir/all] Error 2

```

**Comment by anhttran** [comment]
As described in README.md, you need to "update Dlib directory paths (DLIB_INCLUDE_DIR and DLIB_LIB_DIR) in CMakeLists.txt".

**Comment by QuantumLiu** [comment]
Thank you, i'll check

**Comment by QuantumLiu** [comment]
I set 
```
set (DLIB_INCLUDE_DIR "/usr/local/include/dlib")
set (DLIB_LIB_DIR "/usr/local/lib")
```
and got error 
```
/usr/local/include/dlib/bits/c++config.h:1:45: fatal error: ../dlib_include_path_tutorial.txt: 没有那个文件或目录
 #include "../dlib_include_path_tutorial.txt"
                                             ^
compilation terminated.
modules/PoseExpr/CMakeFiles/PoseExprLib.dir/build.make:62: recipe for target 'modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/utility.cpp.o' failed
make[2]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/utility.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all' failed
make[1]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by wanggongziZeo** [comment]
I update the Dlib directory paths in CmakeLists.txt, and my dlib version is 19.4.
But there's no folder named "/home/anh/Downloads/dlib-19.4/shared_build/dlib", my path is "/home/wgz/dlib-19.4/dlib".
In the processing of make, the same problem occured.
I wonder how to solve the problem to make the executable file TestVisualization.

**Comment by iacopomasi** [comment]
@wanggongziZeo have you changed these two lines in the CMakeList.txt with your path?

`https://github.com/anhttran/3dmm_cnn/blob/master/CMakeLists.txt#L9`

if you did, make sure that you delete the build directory and start from scratch to be sure.
Also, check if there are other hardcoded path inthe CMakeList.txt.
If you have installed dlib, you can try to replace those two lines with `find_package( dlib REQUIRED )`

**Comment by wanggongziZeo** [comment]
Thanks for your reply.
I replace the two lines with find_package(dlib REQUIRED )
The former question worked, but there is another question occured: No rules to make the target /usr/lib/libblas.so
I find my file in this path is libblas.so.3

**Comment by iacopomasi** [comment]
You need to change this `https://github.com/anhttran/3dmm_cnn/blob/master/modules/PoseExpr/CMakeLists.txt#L43` to point to your path.

**Comment by anhttran** [comment]
Also, you need to run cmake again whenever you modify CMakeLists.txt.

**Comment by wanggongziZeo** [comment]
Yeah, I tried your suggestions
But it seems no use to me .I update the Libblas library,and there is libblas.so in my own path,
then I rebuild, and cmake once again, when make, more problem occured:::
/usr/bin/ld: can't find -lfind_package
/usr/bin/ld: can't find -l(
/usr/bin/ld: can't find -ldlib
/usr/bin/ld: can't find -lREQUIRED
/usr/bin/ld: can't find -l)/libdlib.so
Besides the solution, I wnat to specify the toos-version of the project.
Thanks once again.

**Comment by cogito666** [comment]
Hello. 
I am having the same problem.
Is there anybody who solve it?
