### ISSUE TITLE
when Cmake, 92% processing, occuring a problem

### ISSUE THREAD

**Issue by wanggongziZeo** [anhttran/3dmm_cnn#25]
*** No rule to make target '/home/pp/dlib-19.4/dlib/libdlib.so', needed by 'bin/TestVisualization'。
So how to solve the problem?
I use the dlib-19.4,and opencv=2.4.9,other included libraries have been installed.
Thanks for your reply.

**Comment by iacopomasi** [comment]
Take a look here `https://github.com/anhttran/3dmm_cnn/blob/master/modules/PoseExpr/CMakeLists.txt#L44`

**Comment by nelson0707** [comment]
how did you solve this problem？ @wanggongziZeo
