### ISSUE TITLE
Can't download ResNet-101 for 3DMM Regression

### ISSUE THREAD

**Issue by hjy1312** [anhttran/3dmm_cnn#26]
After i submitted my information，then i got the following instruction:
"""
You can access the download page from this link 
[](https://goo.gl/RwU7Nz)
Thank you!
"""
But when i clicked the link above, it told me that:
"""Redirecting you to[]( https://goo.gl/RwU7Nz)"""
And:
"""
[gist.github.com](url) doesn't send any data.
ERR_EMPTY_RESPONSE
"""
Could anyone tell me what should i do to get access to the code? Thank you very much.

**Comment by anhttran** [comment]
You can check the **Download** section of the gist.github.com:
"The CNN model is publicly available and you can **download it here**. If you find our work useful, please remember to cite our paper [1] below."

**Comment by iacopomasi** [comment]
Hi @hjy1312 ,
do you have an email address? I will send you the link in a private message.
Also, note that the code is already publicly available on GitHub. 
The download link is only needed to download the binary CNN model weights used in the code.
 
I tried to reproduce the steps to access the link that for you is broken; for me, all is working.

Best,

**Comment by hjy1312** [comment]
@iacopomasi  Okay. My email address is eehjy1312@mail.scut.edu.cn. Thank you very much!

**Comment by hjy1312** [comment]
@anhttran  Actually I couldn't find this line "The CNN model is publicly available and you can download it here. If you find our work useful, please remember to cite our paper [1] below." in [](https://www.openu.ac.il/home/hassner/projects/CNN3DMM/). Thank you for your reply.

**Comment by hjy1312** [comment]
@anhttran Actually I couldn't find this line "The CNN model is publicly available and you can download it here. If you find our work useful, please remember to cite our paper [1] below." in [https://www.openu.ac.il/home/hassner/projects/CNN3DMM/](url) . Thank you for your reply.

**Comment by anhttran** [comment]
You should find that text in the gist.github.com page after filling the form.
Best,

**Comment by iacopomasi** [comment]
I think all is solved. I emailed him the correct link.

**Comment by hjy1312** [comment]
Thank you！I have got access to the code. I guess there might be something wrong with my net connection.

**Comment by emily1314** [comment]
I can not open the link : gist.github.com, could you mail me the right link ? Thank you so much.
@iacopomasi
