### ISSUE TITLE
 undefined reference to symbol 'dgesdd_'

### ISSUE THREAD

**Issue by mrhossain** [anhttran/3dmm_cnn#28]
/usr/bin/ld: ../modules/PoseExpr/libPoseExprLib.a(DlibWrapper.cpp.o): undefined reference to symbol 'dgesdd_'
/opt/intel/mkl/lib/intel64//libmkl_rt.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
config/CMakeFiles/TestVisualization.dir/build.make:122: recipe for target 'bin/TestVisualization' failed
make[2]: *** [bin/TestVisualization] Error 1
CMakeFiles/Makefile2:196: recipe for target 'config/CMakeFiles/TestVisualization.dir/all' failed
make[1]: *** [config/CMakeFiles/TestVisualization.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by iacopomasi** [comment]
It looks like that the static library `libPoseExprLib.a` cannot find the right symbol for `dgesdd_`. Probably this is a lapack call. Check if opencv and lapack are installed and configured properly or if the system is configured properly. These are linking errors.

**Comment by mrhossain** [comment]
Issue solved after making the depended libraries from static to shared library.

**Comment by sausax** [comment]
Hi @mrhossain, What changes you made to change from static to shared library.
