### ISSUE TITLE
could not download the model: 3dmm_cnn_resnet_101.caffemodel,deploy_network.prototxt,mean.binaryproto

### ISSUE THREAD

**Issue by emily1314** [anhttran/3dmm_cnn#29]
Hi, thank for your sharing your paper and code, after reading the paper, I want to run the code, however, I could not download the caffemodel and prototxt. Can you tell me the link I can download the models? thank you so much.

**Comment by hjy1312** [comment]
Hi,
@emily1314 
I have emailed you the link, please check it.

**Comment by iacopomasi** [comment]
The official link to download the CNN is following this page [https://www.openu.ac.il/home/hassner/projects/CNN3DMM/](https://www.openu.ac.il/home/hassner/projects/CNN3DMM/)

I tried now and it is all working.

**Comment by bettertang** [comment]
sorry , could not download the model now ,can you share the link again? thank you so much

**Comment by anhttran** [comment]
Can you try this?
https://docs.google.com/forms/d/e/1FAIpQLSd6cwKh-CO_8Yr-VeDi27GPswyqI9Lvub6S2UYBRsLooCq9Vw/viewform
Or: https://gist.github.com/iacopomasi/0646722f97fb087926a16b7e044ed6ed

Best,
Anh

**Comment by bettertang** [comment]
thank  @anhttran  I can download the model now!
But when i run  python testBatchModel.py  input.txt output/   in  3dmm_cnn/demoCode
got the Error  

: Prepare image data/1.jpg
Traceback (most recent call last):
  File "testBatchModel.py", line 92, in <module>
    dlib_img = io.imread(image_path)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_io.py", line 62, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 214, in call_plugin
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'data/1.jpg\r'

how can I solve it ?

**Comment by anhttran** [comment]
Look like your "input.txt" uses Windows line ending "\r\n". You should re-download/re-create it in Unix to have Unix line ending ("\n"). Or you can drop the '\r' character at the end of image_path.

**Comment by bettertang** [comment]
extremely grateful @anhttran  ,I run the demo and get the result

**Comment by Zvyozdo4ka** [comment]
> The official link to download the CNN is following this page https://www.openu.ac.il/home/hassner/projects/CNN3DMM/
> 
> I tried now and it is all working.

No, it is not.

![image](https://github.com/anhttran/3dmm_cnn/assets/74532816/46e3e974-f23c-4a97-a887-c4b42fdda342)
![image](https://github.com/anhttran/3dmm_cnn/assets/74532816/ced5e5be-e2ac-432d-91b3-ec111d1a0010)

**Comment by anhttran** [comment]
Dear all,

You could find my Caffe model in this link: [https://drive.google.com/file/d/0BzkHndh8dgoATDZ5TnVRQk5qSkU](https://drive.google.com/file/d/0BzkHndh8dgoATDZ5TnVRQk5qSkU)

Best regards,
Anh

**Comment by Zvyozdo4ka** [comment]
> You could find my Caffe model in this link: https://drive.google.com/file/d/0BzkHndh8dgoATDZ5TnVRQk5qSkU

Thank You!

Is there any chance that you have your CNN model trained in PyTorch? 
I can't use this file: `3dmm_cnn_resnet_101.caffemodel`, as I failed to install Caffe. I  am trying to convert `3dmm_cnn_resnet_101.caffemodel` into pth, but I haven't accomplished this yet.

**Comment by anhttran** [comment]
You can download the PyTorch model version, following the instructions in my another repo: [https://github.com/anhttran/extreme_3d_faces#data-requirements](https://github.com/anhttran/extreme_3d_faces#data-requirements).
