### ISSUE TITLE
F0107 18:26:07.968050  3245 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.

### ISSUE THREAD

**Issue by yashiro32** [anhttran/3dmm_cnn#30]
F0107 18:26:07.968050  3245 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.

*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by iacopomasi** [comment]
Your caffe is compiled in CPU-mode only and you are trying to use it GPU mode.

**Comment by yashiro32** [comment]
Where in your scripts can I change it to use CPU instead of GPU ?

**Comment by iacopomasi** [comment]
search for caffe.set_gpu() and change it to caffe.set_cup()

Also you can help yourself by googling how to do it.
