### ISSUE TITLE
can not download ResNet-101 for 3DMM Regression

### ISSUE THREAD

**Issue by xiaoyun4** [anhttran/3dmm_cnn#31]
After i submitted my information， i got the following instruction:
"""
You can access the download page from this link
https://goo.gl/RwU7Nz
Thank you!
"""
But when i clicked the link above, it told me that:
""
Redirecting you to https://goo.gl/RwU7Nz 
"""
the link doesn't send any data.

 I also see that the same issue occurred for somebody, but  i don't know how to solve it.

Could you tell me what should i do to get access to the code?  thanks

**Comment by YuanWanglll** [comment]
Can you access to Google？
If not，you must try to climb over the wall.

**Comment by iacopomasi** [comment]
@xiaoyun4 
I have updated the Google Form to link to the direct link instead of Google Short Url. 

Can you fill the form and try again?

Thanks.

**Comment by xiaoyun4** [comment]
Yes，  you are right. I has download the files. 
thanks!
