### ISSUE TITLE
error: ‘Rodrigues’ is not a member of ‘cv’

### ISSUE THREAD

**Issue by YuanWanglll** [anhttran/3dmm_cnn#32]
After 

	mkdir build
	cd build
	cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=../bin ..

When I try to “make”
it shows :

       **/3dmm_cnn/modules/PoseExpr/src/BaselFaceEstimator.cpp: In member function ‘void BaselFaceEstimator::estimatePose3D(cv::Mat, cv::Mat, cv::Mat, cv::Mat&, cv::Mat&)’:
       /3dmm_cnn/modules/PoseExpr/src/BaselFaceEstimator.cpp:207:2: error: ‘Rodrigues’ is not a member of ‘cv’
        cv::Rodrigues(rMatP, rVec);**
         ^

**Comment by anhttran** [comment]
Your code may link to OpenCV 3. Please check the "Closed" tickets:
https://github.com/anhttran/3dmm_cnn/issues/21
