### ISSUE TITLE
dlib/image_processing/frontal_face_detector.h: No such file or directory

### ISSUE THREAD

**Issue by xiaoyun4** [anhttran/3dmm_cnn#33]
download dlib-19.4 and python setup.py install.  'import dlib' in python is all ok

and then i update Dlib directory paths (DLIB_INCLUDE_DIR and DLIB_LIB_DIR) in CMakeLists.txt.
set (DLIB_INCLUDE_DIR "/home/xiaoyun/soft/dlib-19.4.0")
But there's no folder named "/...../dlib-19.4/shared_build/dlib", my path is ""/...../dlib-19.4.0/build"".

and then Make build directory (temporary) and Make

the error is ：
/data/yun/speech2video/3dmm_cnn/modules/PoseExpr/include/DlibWrapper.h:7:57: fatal error: dlib/image_processing/frontal_face_detector.h: No such file or directory
 #include <dlib/image_processing/frontal_face_detector.h>
                                                         ^
compilation terminated.
make[2]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/DlibWrapper.cpp.o] Error 1
make[1]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all] Error 2
make: *** [all] Error 2

 but i  can find 'dlib/image_processing/frontal_face_detector.h'.

I wonder how to solve the problem

**Comment by valbi** [comment]
Hello @xiaoyun4,
If you closed this issue, did you find a solution.
For my part, I don't know why "make" not finding dlib/image_processing/frontal_face_detector.h
In the cmakelist.txt, i add : 
set (DLIB_INCLUDE_DIR "/home/<username>/dlib-19.11")
set (DLIB_LIB_DIR "/home/<username>/dlib-19.11/dlib/build")
but with no progress.

**Comment by anlan625** [comment]
Hi, I've got the same problem here.
I am wondering whether you've fixed it. Can you give me a little hint please. Thanks in advance!
