### ISSUE TITLE
fatal error: mkl_dfti.h: No such file or directory

### ISSUE THREAD

**Issue by xiaoyun4** [anhttran/3dmm_cnn#34]
install dlib-19.4.0 and Update Dlib directory paths (DLIB_INCLUDE_DIR and DLIB_LIB_DIR) in CMakeLists.txt

set (DLIB_INCLUDE_DIR "/home/xiaoyun/soft/dlib-19.4.0")
set (DLIB_LIB_DIR "/home/xiaoyun/soft/dlib-19.4.0/dlib/build")

and then Make build directory (temporary) and Make
a error:

[100%] Building CXX object config/CMakeFiles/TestVisualization.dir/__/main.cpp.o
In file included from /usr/local/include/dlib/matrix.h:15:0,
                 from /usr/local/include/dlib/geometry/point_transforms.h:9,
                 from /usr/local/include/dlib/geometry.h:10,
                 from /usr/local/include/dlib/image_processing/object_detector.h:7,
                 from /usr/local/include/dlib/image_processing/frontal_face_detector.h:7,
                 from /data/yun/speech2video/3dmm_cnn/config/../modules/PoseExpr/include/DlibWrapper.h:7,
                 from /data/yun/speech2video/3dmm_cnn/main.cpp:10:
/usr/local/include/dlib/matrix/matrix_fft.h:12:22: fatal error: mkl_dfti.h: No such file or directory
 #include <mkl_dfti.h>
                      ^
compilation terminated.
make[2]: *** [config/CMakeFiles/TestVisualization.dir/__/main.cpp.o] Error 1
make[1]: *** [config/CMakeFiles/TestVisualization.dir/all] Error 2
make: *** [all] Error 2

I wonder how to solve the problem, thanks a lot

**Comment by anhttran** [comment]
You code links to /usr/local/include/dlib instead. Can you try cleaning the "build" folder, runing cmake & make again?

**Comment by xiaoyun4** [comment]
i change the link in Cmakelist.txt like this:

# DEFINE PATH TO YOUR THIRD PARTY LIBs
set (DLIB_INCLUDE_DIR "/usr/local/include/dlib")
set (DLIB_LIB_DIR "/home/xiaoyun/soft/dlib-19.4.0/dlib/build")
     
but an new error:
/usr/local/include/dlib/bits/c++config.h:1:45: fatal error: ../dlib_include_path_tutorial.txt: No such file or directory
 #include "../dlib_include_path_tutorial.txt"
                                             ^
compilation terminated.
make[2]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/utility.cpp.o] Error 1
make[1]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all] Error 2

and  exactly dlib_include_path_tutorial.txt can not find in "/usr/local/include/dlib"

**the process of build dlib;

 download dlib-19.4.0 
cd dlib-19.4/dlib
mkdir build
cd build
cmake ..
make
sudo make install**

i

**Comment by mcoder2014** [comment]
I meet this error too!  
```
set (DLIB_INCLUDE_DIR "/usr/local/include/dlib")
set (DLIB_LIB_DIR "/usr/local/lib")
```

Error logs:
```
root@localhost:~/3dmm/3dmm_cnn/build# cmake -D CMAKE_BUILDTYPE=RELEASE -D CMAKE_INSTALL_PREFIX=../bin ..
OpenCV information:
  OpenCV_INCLUDE_DIRS: /usr/local/include/opencv;/usr/local/include
  OpenCV_LIBRARIES: opencv_videostab;opencv_video;opencv_ts;opencv_superres;opencv_stitching;opencv_photo;opencv_ocl;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
Boost information:
  Boost_INCLUDE_DIRS: /usr/include
  Boost_LIBRARIES: /usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so
  Boost_LIBRARY_DIRS: /usr/lib/x86_64-linux-gnu
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
OPENMP FOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /root/3dmm/3dmm_cnn/build
root@localhost:~/3dmm/3dmm_cnn/build# make && make install
Scanning dependencies of target CvGl
[  7%] Building CXX object modules/CvGl/CMakeFiles/CvGl.dir/FBRender.cpp.o
[ 14%] Linking CXX static library libCvGl.a
[ 14%] Built target CvGl
Scanning dependencies of target PoseExprLib
[ 21%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/utility.cpp.o
In file included from /usr/include/c++/5/iosfwd:38:0,
                 from /usr/include/c++/5/ios:38,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/sstream:38,
                 from /usr/local/include/dlib/assert.h:7,
                 from /usr/local/include/opencv2/core/types_c.h:64,
                 from /usr/local/include/opencv2/core/core_c.h:47,
                 from /usr/local/include/opencv/cv.h:63,
                 from /root/3dmm/3dmm_cnn/modules/PoseExpr/include/utility.h:3,
                 from /root/3dmm/3dmm_cnn/modules/PoseExpr/src/utility.cpp:2:
/usr/local/include/dlib/bits/c++config.h:1:45: fatal error: ../dlib_include_path_tutorial.txt:No such file or directory
compilation terminated.
modules/PoseExpr/CMakeFiles/PoseExprLib.dir/build.make:62: recipe for target 'modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/utility.cpp.o' failed
make[2]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/utility.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all' failed
make[1]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by mcoder2014** [comment]
Oh! This error is solved by change the Path `DLIB_INCLUDE_DIR`

```
set (DLIB_INCLUDE_DIR "/usr/local/include")
set (DLIB_LIB_DIR "/usr/local/lib")
```

But I meet new error 。。。。。

```
root@localhost:~/3dmm/3dmm_cnn/build# make && make install
Scanning dependencies of target CvGl
[  7%] Building CXX object modules/CvGl/CMakeFiles/CvGl.dir/FBRender.cpp.o
[ 14%] Linking CXX static library libCvGl.a
[ 14%] Built target CvGl
Scanning dependencies of target PoseExprLib
[ 21%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/utility.cpp.o
[ 28%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/epnp.cpp.o
[ 35%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/BaselFace.cpp.o
/root/3dmm/3dmm_cnn/modules/PoseExpr/src/BaselFace.cpp:19:19: fatal error: H5Cpp.h: 没有那个文件或目录
compilation terminated.
modules/PoseExpr/CMakeFiles/PoseExprLib.dir/build.make:110: recipe for target 'modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/BaselFace.cpp.o' failed
make[2]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/BaselFace.cpp.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all' failed
make[1]: *** [modules/PoseExpr/CMakeFiles/PoseExprLib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
It is not a good feeling!

**Comment by mcoder2014** [comment]
OK, I found the solution in #20
