### ISSUE TITLE
Unable to download the file in the link

### ISSUE THREAD

**Issue by MoniWong** [anhttran/3dmm_cnn#36]
Hello, dear anhttran, iacopomasi and tangshi
I am about to start my undergraduate design and interested in 3D reconstruction. I read some papers and fortunately find your project. I want to try the effect that you said in the paper, but when I download the file in the link, I encountered some trouble. The process of acquiring 3DDFA Expression Model will always be terminated when the file is downloaded 33.64%. So I sincerely hope whether you can send me this file through email. Thank you very much.

**Comment by anhttran** [comment]
I am sorry that I missed your question. As my understanding, you got a problem when downloading 3DDFA model. You can contact the authors of 3DDFA work to resolve this problem.
