### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by mychina75** [anhttran/3dmm_cnn#37]
Hi, 
Thank you for your work. 
And finally I compiled all files succeed. But there is a link error can not solve.
Can you check the issue? I am not sure if it caused by version of dlib, or openblas.

$ make
[  7%] Building CXX object modules/CvGl/CMakeFiles/CvGl.dir/FBRender.cpp.o
[ 14%] Linking CXX static library libCvGl.a
[ 14%] Built target CvGl
[ 21%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/utility.cpp.o
[ 28%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/epnp.cpp.o
[ 35%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/BaselFace.cpp.o
[ 42%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/BaselFaceEstimator.cpp.o
[ 50%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/FTModel.cpp.o
[ 57%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/FImRenderer.cpp.o
[ 64%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/RenderModel.cpp.o
[ 71%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/FaceServices2.cpp.o
[ 78%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/DlibWrapper.cpp.o
[ 85%] Linking CXX static library libPoseExprLib.a
[ 85%] Built target PoseExprLib
[ 92%] Building CXX object config/CMakeFiles/TestVisualization.dir/__/main.cpp.o
[100%] Linking CXX executable ../bin/TestVisualization
**/usr/bin/ld: ../modules/PoseExpr/libPoseExprLib.a(DlibWrapper.cpp.o): undefined reference to symbol 'dgesdd_'
//usr/lib/libopenblas.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status**
config/CMakeFiles/TestVisualization.dir/build.make:131: recipe for target 'bin/TestVisualization' failed
make[2]: *** [bin/TestVisualization] Error 1
CMakeFiles/Makefile2:196: recipe for target 'config/CMakeFiles/TestVisualization.dir/all' failed
make[1]: *** [config/CMakeFiles/TestVisualization.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mychina75** [comment]
Hi, All
Solved by install LAPACK. And change CMakeLists.txt file. Add this line:
target_link_libraries(PoseExprLib PUBLIC -llapack).

**Comment by sausax** [comment]
@mychina75  Can you post your CMakeLists.txt file ?

**Comment by valbi** [comment]
@sausax the line `target_link_libraries(PoseExprLib PUBLIC -llapack)` must be add in <PATH_TO_3dmm_cnn_FOLDER>/modules/PoseExpr/CMakeLists.txt. 
For my case, i insert it in the line after `target_link_libraries(PoseExprLib PUBLIC -fopenmp)` and `make` works with no error
