### ISSUE TITLE
Installing on MacOS

### ISSUE THREAD

**Issue by Sugarbank** [anhttran/3dmm_cnn#4]
Hi any ideas on installing for MacOs?

**Comment by anhttran** [comment]
Our release model was built on Caffe. You can check how to install Caffe and the other third party libraries on MacOs following the instructions on their sites.
E.g. Caffe: [http://caffe.berkeleyvision.org/install_osx.html](http://caffe.berkeleyvision.org/install_osx.html)
       Dlib  : [http://dlib.net/compile.html](http://dlib.net/compile.html)
