### ISSUE TITLE
TestVisualization: error while loading shared libraries: libdlib.so

### ISSUE THREAD

**Issue by vaheta** [anhttran/3dmm_cnn#40]
I've compiled everything successfully and got testBatchModel.py running. However, when I try testModel_PoseExpr.py, I get the following output
> Prepare image /home/vaheta/builds/3dmm_cnn/demoCode/data/1.jpg:
    Number of faces detected: 1
> CNN Model loaded to regress 3D Shape and Texture!
> Loaded the Basel Face Model to write the 3D output!
/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn(\"The default mode, 'constant', will be changed to 'reflect' in \"
** Caffe loading    : 0.351 s
** Image cropping   : 0.253 s
** 3D Modeling      : 0.741 s
> Writing 3D file in:  out//1.ply
> Pose & expression estimation
./TestVisualization: error while loading shared libraries: libdlib.so.19.10.0: cannot open shared object file: No such file or directory

although dlib was successfully compiled and I put the path to it in CMakeLists.txt. What am I doing wrong? 
Thanks!

**Comment by vaheta** [comment]
Ok, have fix it doing this https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s

**Comment by iacopomasi** [comment]
It is a runtime error. You have a problem when the binary loads shared
libraries.
Make sure that libdlib.so.19.10.0 is in your LD_LIBRARY_PATH.

You can try to 'locate libdlib.so.19.10.0' and export it into the
LD_LIBRARY_PATH to see if that's what is causing the problem.
