### ISSUE TITLE
Getting hdf5 related error while linking

### ISSUE THREAD

**Issue by sausax** [anhttran/3dmm_cnn#41]
I am getting following error while linking 

../modules/PoseExpr/libPoseExprLib.a(BaselFace.cpp.o): In function `readH5Dataset(H5::H5File const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
BaselFace.cpp:(.text+0x8e): undefined reference to `H5::CommonFG::openDataSet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../modules/PoseExpr/libPoseExprLib.a(BaselFace.cpp.o): In function `BaselFace::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
BaselFace.cpp:(.text+0x279e): undefined reference to `H5::Exception::getDetailMsg[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
config/CMakeFiles/TestVisualization.dir/build.make:128: recipe for target 'bin/TestVisualization' failed
make[2]: *** [bin/TestVisualization] Error 1
CMakeFiles/Makefile2:196: recipe for target 'config/CMakeFiles/TestVisualization.dir/all' failed
make[1]: *** [config/CMakeFiles/TestVisualization.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I am building on ubuntu 16.04.

**Comment by anhttran** [comment]
Do you have the h5 generated in the 3DMM_model folder?

**Comment by vipghn4** [comment]
I has the h5 file generated but still get the error above
