### ISSUE TITLE
Script for fast installation on clean ubuntu 16.04

### ISSUE THREAD

**Issue by seva100** [anhttran/3dmm_cnn#43]
@anhttran, huge thanks for open-sourcing this.
I would like to share the [installation script](https://pastebin.com/7yk054AG) for all dependencies of this repository, which I prepared for convenient installation on a clean Ubuntu 16.04, Cuda 9.2 with Conda. 
This is not an issue, rather an improvement which someone might find helpful, as I hope.

#### Installation instructions:
1. Download the repository and recreate additional files, as described on the repository home page
2. Download and install CUDA for Ubuntu 16.04 (9.2 is the current latest version):
```bash
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.2.88-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1604_9.2.88-1_amd64.deb
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
sudo apt-get update
sudo apt-get install cuda
```
3. Download latest Anaconda or Miniconda
4. Do
```bash
conda create -n=3dmm_cnn python=2.7.*
source activate 3dmm_cnn
```
5. Download [install.sh](https://pastebin.com/7yk054AG) to the project folder, where all the files from repository are contained.
6. Then
   `bash install.sh`

The script installs everything in a conda virtual environment `3dmm_cnn`.

**Comment by anhttran** [comment]
Amazing. It will help to solve a lot of installation issues.

I will check and share it to people. Many thanks for your sharing.

**Comment by iacopomasi** [comment]
Many thanks, @seva100. We can create a wiki page on the github with his suggestion! Thanks!

**Comment by iacopomasi** [comment]
Done. https://github.com/anhttran/3dmm_cnn/wiki/Installation-Script

Thanks!

**Comment by seva100** [comment]
I have updated the installation script: https://pastebin.com/xB1bMSVC
It now contains line 78, which I forgot to add initially. It is needed for Caffe to be seen after the installation.

**Comment by iacopomasi** [comment]
Thanks! I replaced it on the wiki page!

**Comment by seva100** [comment]
@anhttran @iacopomasi, however, this script turns out to be not working for the Pose&Expr estimation script (`demoCode/testModelPoseExpr.py`), at least on my machine. Main issue seems to be from OpenCV versions conflict.
May I ask what is the OpenCV version required for the second script?

BTW, I would be very grateful to have a docker container provided by you. I can assist with that if needed.

**Comment by anhttran** [comment]
We use OpenCV 2. OpenCV 3 requires some changes in code.

I am on travel. I will check if I can make the docker file when I have time.

Many thanks,
Anh
