### ISSUE TITLE
/usr/bin/ld: cannot find -lhdf5

### ISSUE THREAD

**Issue by KhanhDinhDuy** [anhttran/3dmm_cnn#44]
Dear all,
Please help me with this issue.
++++++++++++++++++++
 92%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/RenderModel.cpp.o
[ 92%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/FaceServices2.cpp.o
[ 92%] Building CXX object modules/PoseExpr/CMakeFiles/PoseExprLib.dir/src/DlibWrapper.cpp.o
[ 92%] Linking CXX static library libPoseExprLib.a
[ 92%] Built target PoseExprLib
[ 92%] Building CXX object config/CMakeFiles/TestVisualization.dir/__/main.cpp.o
[ 92%] Linking CXX executable ../bin/TestVisualization
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
config/CMakeFiles/TestVisualization.dir/build.make:111: recipe for target 'bin/TestVisualization' failed
make[2]: *** [bin/TestVisualization] Error 1
CMakeFiles/Makefile2:201: recipe for target 'config/CMakeFiles/TestVisualization.dir/all' failed
make[1]: *** [config/CMakeFiles/TestVisualization.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
++++++++++++++++++++
I am facing with this issue when running "make" for building this project.
Thank you,
Khanh

**Comment by iacopomasi** [comment]
Hi @KhanhDinhDuy,
make sure to have all the dependencies. Check it out [here](https://github.com/anhttran/3dmm_cnn#installation-pose--expression-fitting-code).
If you are on a Debian-based distro, install HDF5 with `sudo apt-get install libhdf5-dev`

I hope this helps,
Best
