### ISSUE TITLE
[Qustion] Usage of TestVisualization 

### ISSUE THREAD

**Issue by cogito666** [anhttran/3dmm_cnn#47]
Hello Thanks for sharing this nice project.

I have a question for c++ build result, "TestVisualization".
I checked the main.cpp.

printf("Usage: Visualize3D <imPath> <input 3D alpha> <BaselFace.dat path> <dlib path> [<LM path>]\n");

<imPath>: path to directory which contains image files?
<input 3D alpha>: totally no idea.
<BaselFace.dat path>: path to "01_MorphableModel.mat"?
<dlib path> path to "shape_predictor_68_face_landmarks.dat"?

I need some help to test it. :-)

**Comment by anhttran** [comment]
You can check the demo code (demoCode/testModel_PoseExpr.py) to understand how to use this binary.
Best,
Anh

**Comment by cogito666** [comment]
Thanks for your replay. I asked the question to avoid setting up for caffe.
Noe I finally I get it. 
Thank you. :-)
