### ISSUE TITLE
Asians look alike

### ISSUE THREAD

**Issue by flyingzhao** [anhttran/3dmm_cnn#5]
I test some photos of Chinese. But it seems that everyone looks alike. Shapes between different people are not as discriminative as your examples.

**Comment by TalHassner** [comment]
@flyingzhao there is very little we can do with such a comment. 

What images did you test? What version of the code + CNN were you using? Are you judging the output based on appearance alone (if so, how?) or are you looking at the 3DMM values that were regressed (which are what we claim is discriminative)? These are just a few of things missing for us to know what you may be having problems with. 

So I would suggest that you please see [our paper](https://arxiv.org/abs/1612.04904) for information on the limitations of our approach and the reasons why we claim that its output is discriminative.
