### ISSUE TITLE
Would you please provide the train code for study?

### ISSUE THREAD

**Issue by yyssmm** [anhttran/3dmm_cnn#50]
Thank you for sharing your code, would you please provide the train code for study? Thank you again for you help

**Comment by Beichenxing** [comment]
HI，Can you share 3dmm_cnn_resnet_101.caffemodel,deploy_network.prototxt,mean.binaryproto?Thank you

**Comment by iacopomasi** [comment]
Hi,
you should be able to access them. Please, read here [https://github.com/anhttran/3dmm_cnn#data-requirements](https://github.com/anhttran/3dmm_cnn#data-requirements)

I hope this helps
