### ISSUE TITLE
CNN model is not possible to diwnload

### ISSUE THREAD

**Issue by Zvyozdo4ka** [anhttran/3dmm_cnn#61]
Hello.

On your main page it is written:

[Download our CNN](http://www.openu.ac.il/home/hassner/projects/CNN3DMM) and move the CNN model (3 files: 3dmm_cnn_resnet_101.caffemodel,deploy_network.prototxt,mean.binaryproto) into the CNN folder,

but i always get this problem.

![image](https://github.com/anhttran/3dmm_cnn/assets/74532816/e765e0b3-eedd-4ef1-8228-6853e7cf129b)

Is there any other way to get your CNN?

Or could you explain how did you train your CNN?

**Comment by anhttran** [comment]
Dear,

You could find my Caffe model in this link: [https://drive.google.com/file/d/0BzkHndh8dgoATDZ5TnVRQk5qSkU](https://drive.google.com/file/d/0BzkHndh8dgoATDZ5TnVRQk5qSkU)

Best regards,
Anh
