### ISSUE TITLE
net input data type?

### ISSUE THREAD

**Issue by sunjunlishi** [anhttran/3dmm_cnn#7]
input data is 0~1,or 0~255 or -1~1

**Comment by iacopomasi** [comment]
Hi @sunjunlishi ,
it is very hard to understand your question but I think I got your point.
You should basically subtract from the input image the average image that we provided with the network.
This should solve your problem `input_image_cnn = input_image - average_img`. After subtracting the avg_image you can check the numerical range of values, if you want.

I hope this helps,
iacopo

**Comment by anhttran** [comment]
Dear @sunjunlishi,
You should check and follow our demo code. Basically, the input data is scaled to [0,255] and subtracted by mean. Also, the channels are swapped:

"transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
transformer.set_transpose('data', (2,0,1))
transformer.set_channel_swap('data', (2,1,0))
transformer.set_raw_scale('data', 255.0)
transformer.set_mean('data',mean)"

I hope this helps,
Anh

**Comment by sunjunlishi** [comment]
my meaning is input data's range.your answer is ok.0～255.0 and subtract buy mean

**Comment by sunjunlishi** [comment]
thank you

**Comment by sunjunlishi** [comment]
transformer.set_transpose('data', (2,0,1)),how to do?

**Comment by anhttran** [comment]
It simply swaps your image dimensions, from H x W x C (H: height, W: width, C: the number of channels) to C x H x W.

**Comment by sunjunlishi** [comment]
testing in several imgs ,why my net output is same ?
![Uploading 1.png…]()

**Comment by sunjunlishi** [comment]
so that all the 3d result is same
![2](https://cloud.githubusercontent.com/assets/11845664/25657170/1139897a-302f-11e7-845d-bc9fdd14ca04.png)

**Comment by iacopomasi** [comment]
Hi @sunjunlishi ,
could you please be a bit more specific in the issue that you are reporting? I am not sure if it is on our side, the code works well for other people and you get 3DMM-like prediction which correlates with the input image. First of all, we do not have under this project C++ code that you are showing in your window. Our code is python.

I suspect that you are getting every time the average face model from Basel Face Model, instead of the Net output; if I were you, I'd check more on that; of course, it is hard to tell from your info.

I hope this helps,
Best.

**Comment by sunjunlishi** [comment]
the prepared image,i used yours.if only net predict ,it will work.
i will in ubuntu python,if i do not succeess yet in windows c++

**Comment by sunjunlishi** [comment]
i think my input data wrong,so all net predict same

**Comment by sunjunlishi** [comment]
my WxHxC,yours CxWxH

**Comment by sunjunlishi** [comment]
windows not ok,ubuntu okfile:///home/sun/down/2017-05-04%2020-29-35%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png
file:///home/sun/down/2017-05-04%2020-32-19%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png

**Comment by sunjunlishi** [comment]
my c++ result code：
	PNet_->Forward();
	shared_ptr<Blob<float>> reg = PNet_->blob_by_name("fc_ftnew");
	int iCount = reg->count();
	const float* reg_data = reg->cpu_data();
	std::vector<float> fR;
	for (int k = 0; k < iCount; ++k)
	{
		fR.push_back(reg_data[k]);
	}

**Comment by sunjunlishi** [comment]
ok,l resolve it.i change caffe,it ok

**Comment by sunjunlishi** [comment]
thank you
