### ISSUE TITLE
Could be 3d mode  trimed as float type，it will be smaller。and Could DNN model more smaller 

### ISSUE THREAD

**Issue by sunjunlishi** [anhttran/3dmm_cnn#8]
Could be 3d mode  trimed as float type，it will be smaller。and Could DNN model more smaller 。
it will more smart using
![qq 20170514182655](https://cloud.githubusercontent.com/assets/11845664/26032993/90be8a36-38d3-11e7-94c8-e895e6472446.jpg)

**Comment by TalHassner** [comment]
@sunjunlishi we really don't understand what you mean. In the future, please try to be clearer with your questions (contributions?) and we will be happy to try and help.

**Comment by sunjunlishi** [comment]
firstly,BaselFaceModel_mod.mat is 116M,it's data has double type,change to float ,could be more smaller
secondly: 3dmm_cnn_resnet_101.caffemodel is 172M,could be more smaller,to 10M;
so that,so that many many  using based on your method

**Comment by sunjunlishi** [comment]
I have a note, multiple photos from different angles, using your method to calculate the results, weighted addition, is not the final result will be better?. And if the texture is added, is the effect better?. Your work is great

**Comment by TalHassner** [comment]
@sunjunlishi RE smaller size files, you are correct. BFM, however, is not ours to distribute. Reducing the size of a deep network is something we are considering, but I think it may require more than just using smaller variable types to to this right without changing the quality of the output. 

RE several photos from different angles, yes, in our experience that seemed to help a lot. Also using texture improved the results too.

**Comment by sunjunlishi** [comment]
could The ave pooling replaces the full join layer ,to that reduce mode's size
