### ISSUE TITLE
Error in load BFM mat file

### ISSUE THREAD

**Issue by samsgates** [anhttran/3dmm_cnn#9]
How to solve this error ?

CNN Model loaded to regress 3D Shape and Texture!
/usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py:130: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.indices) != 1 or np.rank(self.indptr) != 1:
Traceback (most recent call last):
  File "demo.py", line 153, in <module>
    model = model["BFM"]
KeyError: 'BFM'

**Comment by anhttran** [comment]
Hi,

Did you generate BaselFaceModel_mod.mat following the instructions?
"Copy the Basel Face Model (01_MorphableModel.mat) in the same folder of demo.py file.
Run the script python trimBaselFace.py. This should output a file BaselFaceModel_mod.mat and remove the original one automatically."

**Comment by samsgates** [comment]
got it. problem solved. 

thanks

**Comment by anhttran** [comment]
Glad to hear it :)
